Create V1
betagouv/a-just pull request #27
Opened 2021-12-08 11:20 UTC by fxmontigny

2021-12-08 13:32 UTC, vviers commented on api/config/default.js
> +    private_key: 'ghjklmlmtyuikopl^mù$',
c'est ok de pousser ça en clair sur GitHub ?

2021-12-08 13:36 UTC, vviers commented on front/src/app/components/referentiel-calculator/referentiel-calculator.component.ts
> +    this.realCover = fixDecimal(this.totalOut / this.totalIn);
Taux de couverture = Coverage en anglais

2021-12-08 13:38 UTC, vviers commented on front/src/app/components/referentiel-calculator/referentiel-calculator.component.ts
> +    this.realDTES = fixDecimal(this.totalStock / this.totalOut / this.nbMonth);
`realDTESInMonths` ?

ou un commentaire pour préciser qu'on est en mois ?

2021-12-08 13:39 UTC, vviers commented on front/src/app/components/referentiel-calculator/referentiel-calculator.component.ts
> +    this.realDelay = fixDecimal(
`realTimePerCase` ?

2021-12-08 13:39 UTC, vviers commented on front/src/app/components/referentiel-calculator/referentiel-calculator.component.ts
> +    this.realDelay = fixDecimal(
c'est pas un délai c'est le temps moyen par dossier non ?

2021-12-08 13:51 UTC, fxmontigny commented on api/config/default.js
> +    private_key: 'ghjklmlmtyuikopl^mù$',
Mince, j'avais zappé. On en avait déjà parlé. Je prend en compte

2021-12-08 13:53 UTC, fxmontigny commented on front/src/app/components/referentiel-calculator/referentiel-calculator.component.ts
> +    this.realCover = fixDecimal(this.totalOut / this.totalIn);
:D j'ai été trop feignant pour écrire le mot en entier

2021-12-08 13:58 UTC, fxmontigny commented on front/src/app/components/referentiel-calculator/referentiel-calculator.component.ts
> +    this.realDelay = fixDecimal(
Oui bien raison

2021-12-08 14:00 UTC, fxmontigny commented
> Est-ce que merger dans main implique qu'on déploie le service "en prod" ? ou c'est juste une release GH ?

Je ne connais pas GH. La main est bien lié à la prod. 
Si tu approuve, je vais fusionner qu'a partir du moment où j'aurai push mes modifs via une autre PR.

2021-12-08 16:19 UTC, vviers commented on api/config/default.js
> +    private_key: 'ghjklmlmtyuikopl^mù$',
Si jamais c'est pas OK, il faut changer la clé

2021-12-08 16:22 UTC, vviers commented on api/config/development.js
> +    private_key: 'ghjklmlmtyuikopl^mù$',
La clé est toujours en clair sur GitHub

Tu peux la mettre dans ton `.env` (qui est bien ignoré par git) ?

Il faut aussi révoquer la clé car maintenant tout le monde a pu la voir :/

2021-12-08 16:23 UTC, vviers commented on api/config/staging.js
> +    private_key: 'ghjklmlmtyuikopl^mù$',
idem ici

2021-12-08 16:25 UTC, vviers requested changes
https://stackoverflow.com/questions/39829221/jwt-config-secret-file-push-on-git

2021-12-09 14:29 UTC, fxmontigny commented on api/config/development.js
> +    private_key: 'ghjklmlmtyuikopl^mù$',
Sans soucis, je fais ça

2021-12-09 14:31 UTC, fxmontigny commented
J'ajoute le JWT dans la procédure d'initialisation du projet

2021-12-09 14:46 UTC, fxmontigny commented on api/config/development.js
> +    private_key: 'ghjklmlmtyuikopl^mù$',
Voilà j'ai supprimé les tokens générés et changé la clée

2021-12-13 08:46 UTC, vviers approved these changes
lgtm

2021-12-14 07:56 UTC, merged